# Generated by Django 3.1.6 on 2021-06-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(default='', max_length=40)),
                ('phone_number', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='', max_length=100)),
                ('hospital_address', models.CharField(default='', max_length=100)),
                ('phone_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default='', max_length=30)),
                ('employee_phone_number', models.IntegerField(default=0)),
                ('employee_Address', models.CharField(default='', max_length=100)),
                ('employee_position', models.CharField(default='', max_length=20)),
                ('hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beng.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='bloodrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('bld_typ_req', models.CharField(default='', max_length=3)),
                ('recipient_name', models.CharField(default='', max_length=20)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beng.employee')),
                ('hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beng.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='blooddetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb_blood', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=3)),
                ('blood_bag_number', models.IntegerField(default=0)),
                ('date_extracted', models.DateTimeField()),
                ('remarks', models.CharField(default='', max_length=100)),
                ('donor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beng.donor')),
            ],
        ),
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('telephone_number', models.IntegerField(default=0)),
                ('blood_bank_address', models.CharField(default='', max_length=100)),
                ('quantity_received', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=40)),
                ('blood_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beng.blooddetails')),
            ],
        ),
    ]
